# fly.toml app configuration file generated for instalog on 2023-10-17T14:54:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "instalog"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
